import MainCarousel from "@/components/home/MainCarousel";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return <MainCarousel />;
}
