import MainCarousel from "@/components/home/MainCarousel";
import TherapyList from "@/components/home/TherapyList";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <MainCarousel />
      <div>메인페이지</div>
      <TherapyList />
    </>
  );
}
